### ISSUE TITLE
Is "jdk.format.settingsPath" working?

### ISSUE THREAD

**Issue by knowbits** [oracle/javavscode#14]
Trying out Oracle's new "Java Platform Support" extension for VS Code. 

Great to see support for recent and upcoming JDKs, including preview features.  Thanks for your effort!

Under "Feature contributions" on the extension's page in VS Code, the following setting is listed: 

   jdk.format.settingsPath   :  Path to the file containing exported formatter settings

I briefly tried to set my Java source code formatting to "Google Java Style" by setting "jdk.format.settingsPath" in my "Workspace settings JSON" file: 

    "jdk.format.settingsPath": "~/.vscode/eclipse-java-google-style.xml"

PS! This file is a modified version of the "Java Google Style" downloaded from: 
      https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml
      
However, the formatting rules in my local "eclipse-java-google-style.xml" does not seem to be used. For instance indentation is changed to 4 spaces, instead of 2 spaces (my preference), when saving a .java source file.

Is it possible to use the "jdk.format.settingsPath" in this version of the extension?

**Comment by vkdot** [comment]
Hi @knowbits 
It seems the Oracle's Java Platform Support extension is based on Netbeans [1], so the Eclipse formatter XML does not work. However, if you export formatter settings from Netbeans as a zip file, then it works. It is just hard to convert from Eclipse to Netbeans formatter if you want to retain the same configuration.

[1] https://netbeans.apache.org/

**Comment by lahodaj** [comment]
As @vkdot says, at this time, the only supported formatter is the NetBeans formatter, so the setting would need to be exported NetBeans support.

**Comment by vkdot** [comment]
If you have Windows, I defined the path as `C:/Users/user/Documents/netbeans-config-export.zip` instead of `C:\Users\user\Documents\netbeans-config-export.zip`.

If you are exporting from Netbeans, you need to select these options (at least this worked for me):
![image](https://github.com/oracle/javavscode/assets/1546832/7794f35f-6d9b-4627-af28-763d1489e0c4)

**Comment by Achal1607** [comment]
I have created a wiki page that provides the steps for custom formatter: [Java formatting preferences](https://github.com/oracle/javavscode/wiki/Java-formatting-preferences) . Thank you so much @knowbits for providing the steps.

**Comment by darchangels13** [comment]
I'm honestly surprised that this Wiki goes on so long.  Let me propose the following edit:

Step 2: Use Netbeans instead

Installing another editor for the sole purpose of configuring your code formatter for the IDE you're actually using is a staggeringly bad UX "solution".  Either adopt the Eclipse-Formatter standard create a vehicle for editing the formatting within VS Code. Or just remove formatting from your plugin entirely so that it's not in conflict with third party options and leave it to other people to solve.

**Comment by ArmoredPony** [comment]
yes please eclipse formatter config support would be very great to have
