### ISSUE TITLE
Wrong instructions to build the extension

### ISSUE THREAD

**Issue by anthonyvdotbe** [oracle/javavscode#223]
As was already brought up in #140, in the build instructions at https://github.com/oracle/javavscode/blob/main/BUILD.md#fetching-and-building-netbeans-code the line `cd ..` must be removed.

**Comment by Achal1607** [comment]
You need to clone NetBeans into the top-level `javavscode` directory. Since the `ant` targets are located in this directory, return to it after checking out the appropriate branch in NetBeans. Due to that `cd..` comes in the build steps.

If you find this comment useful then we can add a new `cd javavscode` step in `BUILD.md` steps to avoid future confusion.

**Comment by anthonyvdotbe** [comment]
Thanks for your explanation, I get it now and created a PR to clarify the steps a bit.

**Comment by arvindaprameya** [comment]
Thank you for your contribution @anthonyvdotbe !!
