### ISSUE TITLE
Lombok support

### ISSUE THREAD

**Issue by ikilinc** [oracle/javavscode#42]
Some our Projects using lombok lib.  Is there a way to use it with this extension?

**Comment by lahodaj** [comment]
Having Lombok on classpath might possibly work, but there's often a problem with the specific Lombok version not supporting the version of javac used by NetBeans (as Lombok depends on javac internals).

**Comment by pbodnar** [comment]
It looks like that a more generic issue #83 got created in the meantime. I guess that this one, as well as another de-facto duplicate #94, can be closed then?

**Comment by Achal1607** [comment]
This extension is focused towards Java development and directly Java related issues, Lombok doesn't follow Java so closing this issue. But if you have face any Java related or extension related issue please feel free to open an issue.

**Comment by jcedenopyx** [comment]
so, there just isn't a world where lombok will be supported by this extension? The [Language Support for Java(TM) by RedHat](https://marketplace.visualstudio.com/items?itemName=redhat.java) extension has built-in support for Lombok and automatically uses the lombok.jar from your project classpath. There are thousands of developers that simply can't use this extension, which is by all intents and purposes superior, because of your refusal to support it
